@startuml
class AutomobileInventory {
- ArrayList<Automobile> inventory
- String makesList
~ boolean overrideMake
+ ArrayList<Automobile> getInventory()
+ void menu(Scanner,ArrayList<Automobile>)
+ ArrayList<Automobile> importInventory(Scanner,ArrayList<Automobile>,boolean)
~ List<String> importMakesList()
+ String[] listInventory(Scanner,ArrayList<Automobile>)
+ AutomobileInventory addAutomobile(AutomobileInventory,Automobile)
+ ArrayList<Automobile> addAutomobile(Scanner,ArrayList<Automobile>)
+ boolean duplicateVin(String,ArrayList<Automobile>)
~ Automobile addMake(Scanner,Automobile)
~ Automobile addModel(Scanner,Automobile)
~ Automobile addColor(Scanner,Automobile)
~ Automobile addYear(Scanner,Automobile)
~ Automobile addMileage(Scanner,Automobile)
+ ArrayList<Automobile> removeAutomobile(Scanner,ArrayList<Automobile>)
+ ArrayList<Automobile> removeAutomobile(ArrayList<Automobile>,String)
+ ArrayList<Automobile> updateAutomobile(Scanner,ArrayList<Automobile>)
+ void saveInventory(Scanner,ArrayList<Automobile>)
+ void quit(Scanner,ArrayList<Automobile>)
+ {static} void automobileInventory()
+ {static} void main(String[])
}
@enduml