@startuml
class edu.csuglobal.AutomobileInventory {
- ArrayList<Automobile> inventory
- String makesList
+ <<Create>> AutomobileInventory()
+ <<Create>> AutomobileInventory(ArrayList<Automobile>)
+ ArrayList<Automobile> getInventory()
+ void setInventory(ArrayList<Automobile>)
+ void menu(Scanner,AutomobileInventory)
+ ArrayList<Automobile> importInventory(ArrayList<Automobile>,boolean)
+ List<String> importMakesList(boolean)
+ void listInventory(AutomobileInventory)
+ void addAutomobile(AutomobileInventory,Automobile)
+ ArrayList<Automobile> addAutomobile(Scanner,ArrayList<Automobile>)
~ String enterVin(Scanner,String)
+ boolean duplicateVin(String,ArrayList<Automobile>)
+ Automobile addMake(Scanner,Automobile)
+ Automobile addModel(Scanner,Automobile)
+ Automobile addColor(Scanner,Automobile)
+ Automobile addYear(Scanner,Automobile)
+ Automobile addMileage(Scanner,Automobile)
+ ArrayList<Automobile> removeAutomobile(Scanner,ArrayList<Automobile>)
+ ArrayList<Automobile> removeAutomobile(ArrayList<Automobile>,String)
+ void updateAutomobile(Scanner,AutomobileInventory)
+ void saveInventory(ArrayList<Automobile>)
+ void quit(Scanner,ArrayList<Automobile>)
+ {static} void automobileInventory()
+ {static} void main(String[])
}
class edu.csuglobal.Automobile {
- String vin
- String make
- String model
- String color
- Year year
- int mileage
+ <<Create>> Automobile()
+ <<Create>> Automobile(String,String,String,String,Year,int)
+ void setVin(String)
+ void setMake(String)
+ void setModel(String)
+ void setColor(String)
+ void setYear(Year)
+ void setMileage(int)
+ String getVin()
+ String getMake()
+ String getModel()
+ String getColor()
+ Year getYear()
+ String getYearAsString()
+ int getMileage()
+ String[] getAutomobile()
+ String toString()
}
@enduml